#!/bin/bash

RED="\033[1;31m"
GREEN="\033[1;32m"
NOCOLOR="\033[0m"

set -e

echo ""
echo -e " ${GREEN}### Installation de MariaDB, Nginx et Php-7.2${NOCOLOR}"
echo ""

while true; do
  read -p "Voulez-vous installer MariaDB [O/n] ? " mariadb_choice
  case $mariadb_choice in
    [Oo]* )
      echo -e " ${GREEN}### Installation de MariaDB${NOCOLOR}"
      apt install mariadb-server mariadb-client --yes
      echo ""
      echo -e " ${GREEN}### Securisation de MariaDB${NOCOLOR}"
      mysql_secure_installation
      systemctl restart mariadb.service
      break;;
    [Nn]* ) break ;;
  esac
done

while true; do
  echo ""
  read -p "Voulez-vous installer Nginx [O/n] ? " nginx_choice
  case $nginx_choice in
    [Oo]* )
      echo ""
      echo -e " ${GREEN}### Installation de Nginx${NOCOLOR}"
      read -p "Quelle est l'URL du serveur (ex: www.petitsurfeur.net) ? " url_server_choice
	apt install nginx --yes

	if [ ! -f /etc/nginx/sites-available/default.SAVE ]; then
	  mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.SAVE
	  cp default /etc/nginx/sites-available/
	 fi

	sed -i "s/server_name XXX.COM;/server_name $url_server_choice;/" /etc/nginx/sites-available/default
	systemctl restart nginx.service
	break ;;
    [Nn]* ) break ;;
  esac
done

while true; do
  echo ""
  read -p "Voulez-vous installer PHP-7.1 [O/n] ? " php71_choice
  case $php71_choice in
    [Oo]* )
      echo ""
      echo -e " ${GREEN}### Installation de PHP-7.1${NOCOLOR}"
	apt install apt-transport-https ca-certificates --yes
	wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
	sh -c 'echo "deb https://packages.sury.org/php/ stretch main" > /etc/apt/sources.list.d/php.list'
	apt update
        apt install php7.1-apcu php7.1-bcmath php7.1-cli php7.1-curl php7.1-fpm php7.1-gd php7.1-intl php7.1-mcrypt php7.1-mysql php7.1-soap php7.1-xml php7.1-zip --yes
	
      echo ""
      read -p "Voulez-vous configurer Nginx (memory_limit, upload_max,...) dans /etc/php/7.1/fpm/php.ini [O/n] ? " php71_config_choice

	  if [[ "$php71_config_choice" = 'O' ]]; then
            cp /etc/php/7.1/fpm/php.ini /etc/php/7.1/fpm/php.ini.SAVE
            sudo sed -i "s/memory_limit = .*/memory_limit = 256M/" /etc/php/7.1/fpm/php.ini
            sudo sed -i "s/upload_max_filesize = .*/upload_max_filesize = 128M/" /etc/php/7.1/fpm/php.ini
            sudo sed -i "s/zlib.output_compression = .*/zlib.output_compression = on/" /etc/php/7.1/fpm/php.ini
            sudo sed -i "s/max_execution_time = .*/max_execution_time = 18000/" /etc/php/7.1/fpm/php.ini

	    nginx -t
            systemctl restart nginx.service
          fi
      break ;;
    [Nn]*) break ;;
  esac
done

while true; do
  echo ""
  read -p "Voulez-vous installer PHP-7.2 [O/n] ? " php72_choice
  case $php72_choice in
    [Oo]* )
      echo -e " ${GREEN}### Installation de PHP-7.2${NOCOLOR}"
      apt install apt-transport-https ca-certificates --yes
      wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
      sh -c 'echo "deb https://packages.sury.org/php/ stretch main" > /etc/apt/sources.list.d/php.list'
      apt update

      apt install php7.2-apcu php7.2-bcmath php7.2-cli php7.2-curl php7.2-fpm php7.2-gd php7.2-intl php7.2-mysql php7.2-soap php7.2-xml php7.2-zip --yes

      echo ""
      read -p "Voulez-vous configurer Nginx (memory_limit, upload_max,...) dans /etc/php/7.2/fpm/php.ini [O/n] ? " php72_config_choice
	if [[ "$php72_config_choice" = 'O' ]]; then
	  cp /etc/php/7.2/fpm/php.ini /etc/php/7.2/fpm/php.ini.SAVE
	  sudo sed -i "s/memory_limit = .*/memory_limit = 256M/" /etc/php/7.2/fpm/php.ini
	  sudo sed -i "s/upload_max_filesize = .*/upload_max_filesize = 128M/" /etc/php/7.2/fpm/php.ini
	  sudo sed -i "s/zlib.output_compression = .*/zlib.output_compression = on/" /etc/php/7.2/fpm/php.ini
	  sudo sed -i "s/max_execution_time = .*/max_execution_time = 18000/" /etc/php/7.2/fpm/php.ini
	  nginx -t     
	  sudo systemctl restart nginx.service
        fi
      break ;;
    [Nn]* ) break ;;
  esac
done

while true; do
  echo ""  
  read -p "Voulez-vous installer Phpmyadmin [O/n] ? " phpmyadmin_choice
  case $phpmyadmin_choice in
    [Oo]* )
      echo ""
      echo -e " ${GREEN}### Installation de Phpmyadmin${NOCOLOR}"
      apt install phpmyadmin --yes
      cp phpmyadmin.conf /etc/nginx/conf.d/
      read -p "Quelle est l'URL du serveur (ex: www.petitsurfeur.net) ? " url_server_choice
      sed -i "s/server_name pma.example.com;/server_name $url_server_choice;/" /etc/nginx/conf.d/phpmyadmin.conf
      echo ""
      nginx -t
      systemctl restart nginx.service
      break ;;
    [Nn]* ) break ;;
  esac
done

