#!/bin/bash

RED="\033[1;31m"
GREEN="\033[1;32m"
NOCOLOR="\033[0m"

echo

echo -e "Etape 1: ${GREEN}pre-configure les paquetages${NOCOLOR}"
sudo dpkg --configure -a

echo

echo -e "step 2: ${GREEN}corrige les problèmes de dépendances${NOCOLOR}"
sudo apt install -f

echo

echo -e "step 3: ${GREEN}met-à-jour le cache apt (update)${NOCOLOR}"
sudo apt update

echo

echo -e "step 4: ${GREEN}met-à-jour les paquetages (upgrade)${NOCOLOR}"
sudo apt upgrade --yes

echo

echo -e "step 5: ${GREEN}met-à-jour la distribution (dist-upgrade)${NOCOLOR}"
sudo apt dist-upgrade --yes

echo

echo -e "step 6: ${GREEN}supprime les paquetages inutiles (autoremove)${NOCOLOR}"
sudo apt-get --purge autoremove --yes

echo

echo -e "step 7: ${GREEN}nettoie (autoclean)${NOCOLOR}"
sudo apt-get autoclean

echo
